version: 2.0

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                  - build
                filters:
                  branches:
                    only: circleci
jobs:
  build:
    machine: true 
        # - image: circleci/golang:1.14.4
    #working_directory: /go/src/github.com/renegmed/learn-go-webservice/inventoryservice
    steps:

        - checkout 

        - run: 
            name: Install latest go 
            command: |
                wget https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz
                sudo tar -xvf go1.14.1.linux-amd64.tar.gz
                sudo rm -rf /usr/local/go 
                sudo mv go /usr/local
                go version

        - run: 
            name: Create work directory, move source code to work directory, then go to work directory 
            command: | 
              mkdir -p /home/circleci/.go_workspace/src/github.com/renegmed             
              mv /home/circleci/project /home/circleci/learn-go-webservice
              mv /home/circleci/learn-go-webservice /home/circleci/.go_workspace/src/github.com/renegmed
              cd /home/circleci/.go_workspace/src/github.com/renegmed/learn-go-webservice
               
        # activate Remote Docker Environment
        # - setup_remote_docker      
        # - run: 
        #     name: Install Docker Compose 
        #     command: | 
        #       set -x curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > sudo /usr/local/bin/docker-compose chmod +x /usr/local/bin/docker-compose
       
        - run:
            name: Start creating images and containers
            command: docker-compose up --build -d 

        - run:
            name: Set GOROOT
            command: export GOROOT="/usr/local/go"    
        - run:
            name: Inquire container status, GOPATH and GOROOT
            command: docker ps -a && echo $GOPATH  && echo $GOROOT

        - run:
            name: Inquire GOPATH and add to PATH
            command: echo $GOPATH && export PATH="$PATH:$GOROOT/bin"

        - run:
            name: Do Test 
            command: cd inventory-service && make test 
